### ISSUE TITLE
Thread 'main' panicked at 'not implemented: not impl mainnet config yet.', cli/src/command.rs:51

### ISSUE THREAD

**Issue by Bourkey290** [chainx-org/documentation#16]
Got this error when executing node...

====

Version: 2.0.0-beta.2-4fa3d9bd-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475:5
   5: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429:5
   6: chainx_cli::command::load_spec
   7: sc_cli::config::CliConfiguration::create_configuration
   8: sc_cli::SubstrateCli::create_runner
   9: chainx_cli::command::run
  10: chainx::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51:25
  14: main
  15: __libc_start_main
  16: _start

Thread 'main' panicked at 'not implemented: not impl mainnet config yet.', cli/src/command.rs:51

This is a bug. Please report it at:

https://github.com/chainx-org/ChainX/issues/new

**Comment by liuchengxu** [comment]
You have to use `--chain=testnet` at this moment, the mainnet is not ready.
